# ---------------------------------------------------------------------------
# We are using "NewPeerOrgs" instead of "PeerOrgs"
# ---------------------------------------------------------------------------
NewPeerOrgs:
  - Name: Valhalla
    Domain: valhalla.asgard
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Cimmeria
    Domain: cimmeria.hage
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
