{{- range $i, $org := .Values.PeerOrgs }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-ca--{{ $org.Name | lower }}-tls
  labels:
    orgName: {{ $org.Name }}
data:
  cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/ca/ca.%s-cert.pem" $org.Domain $org.Domain ) | b64enc }}
  {{- range $path, $bytes := $.Files.Glob (printf "crypto-config/peerOrganizations/%s/ca/*_sk" $org.Domain ) }}
  private_key: |-
      {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
{{- end }} {{- /* Orgs */ -}}
