apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-channels
data:
{{- range $i, $channel := .Values.network.channels }}
  {{ $channel.name }}.tx: |-
      {{ $.Files.Get (printf "channel-artifacts/%s/%s.tx" $channel.name $channel.name) | b64enc }}
{{- end }} {{- /* network.channels */ -}}
