{{- if .Values.couchdb.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hlf-couchdb--ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{- range $i, $org := .Values.PeerOrgs }}
{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- range $peerIndex := untilStep $peerStartIndex (add $peerStartIndex $org.Template.Count | int) 1 }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}
  - host: hlf-couchdb-{{ $org.Name | lower }}-{{ $peer | lower }}.{{ $.Values.ingress.parentDomain }}
    http:
      paths:
      - path: /
        backend: 
          serviceName: hlf-couchdb--{{ $org.Name | lower }}--{{ $peer | lower }}
          servicePort: 5984
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}{{""}}
  tls:
  - hosts:
{{- range $i, $org := .Values.PeerOrgs }}
{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- range $peerIndex := untilStep $peerStartIndex (add $peerStartIndex $org.Template.Count | int) 1 }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}
    - hlf-couchdb-{{ $org.Name | lower }}-{{ $peer | lower }}.{{ $.Values.ingress.parentDomain }}
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}{{""}}
    secretName: hlf-couchdb--ingress-tls
{{- end }} {{- /* if ingress.enabled */ -}}
