{{- range $i, $org := .Values.OrdererOrgs }}
{{- $hostname := (index $org.Specs 0).Hostname -}}
{{- $commonName := (not (index $org.Specs 0).CommonName) | ternary (printf "%s.%s" $hostname $org.Domain) (index $org.Specs 0).CommonName }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-orderer--{{ $org.Name | lower }}-tls
  labels:
    orgName: {{ $org.Name }}
data:
  {{ ($.Files.Glob (printf "crypto-config/ordererOrganizations/%s/orderers/%s/tls/*" $org.Domain $commonName)).AsSecrets | nindent 2 }}
---
{{- end }} {{- /* Orgs */ -}}
