{{- range $i, $org := .Values.OrdererOrgs }}
{{- $hostname := (index $org.Specs 0).Hostname -}}
{{- $commonName := (not (index $org.Specs 0).CommonName) | ternary (printf "%s.%s" $hostname $org.Domain) (index $org.Specs 0).CommonName }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-orderer--{{ $org.Name | lower }}-msp
  labels:
    orgName: {{ $org.Name }}
    commonName: {{ $commonName }}
data:
  cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/signcerts/%s-cert.pem" $org.Domain $commonName $commonName ) | b64enc }}
  cacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/cacerts/ca.%s-cert.pem" $org.Domain $commonName $org.Domain) | b64enc }}
  admincert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/admincerts/Admin@%s-cert.pem" $org.Domain $commonName $org.Domain ) | b64enc }}
  {{- range $path, $bytes := $.Files.Glob (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/keystore/*" $org.Domain $commonName ) }}
  key.pem: |-
      {{ $.Files.Get $path | b64enc }}
  {{- end }}
---
{{- end }} {{- /* Orgs */ -}}
