# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# number of times to retry a failed leaf task
# especially on high end machines install step frequently fails, that's why this number is high
# see https://jira.hyperledger.org/browse/FAB-15026
retryCount: 20

hyperledgerVersion: 1.4.1

# no effect for now
tlsEnabled: false

flow:
  chaincode:
    # should we run top level chaincode flows in parallel?
    parallel: false
    # fill in this array with chaincode names to limit the chaincode flows only to these ones
    include: []
  install:
    # should we run install step?
    enabled: true  
    parallel: true
  instantiate:
    # should we run instantiate step?
    enabled: true  
    parallel: true
  upgrade:
    # should we run upgrade step? upgrade and instantiate should be mutually exclusive
    enabled: false  
    parallel: true
  invoke:
    # should we run invoke step? 
    # we invoke chaincode after instantiate/upgrade to force the peers to actually create the chaincode containers
    enabled: true 
    parallel: true
    function: '{"function":"ping","Args":[""]}'

chaincode:
  version: "1.0"
  language: node
