# Default values for hlf-kube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# number of times to retry a failed leaf task
retryCount: 4

hyperledgerVersion: 1.4.1

# no effect for now
tlsEnabled: false

flow:
  channel:
    # should we run top level channel flows in parallel? 
    # dont set to true if you are using Kafka orderer (as of HL 1.4.0)
    parallel: false
  join: 
    # run channel join flows in parallel? 
    parallel: true
  update: 
    # run channel update flows in parallel? 
    parallel: true

